// src/components/Settings.jsx
import React, { Component } from 'react';

class Settings extends Component {
  constructor() {
    super();
    this.state = {
      link: ''
    };
  }

  handleChange(event) {
    this.setState({ link: event.target.value });
  }

  componentWillMount() {}

  render() {
    return (
      <div className="container mt-3" style={{ width: '500px' }}>
        <div className="form-group">
          <label htmlFor="ipadress">IP Adresse</label>
          <input
            className="form-control"
            type="text"
            placeholder="127.0.0.1"
            id="ipadress"
          />
        </div>
        <div className="form-group">
          <label htmlFor="port">Port</label>
          <input
            className="form-control"
            type="text"
            placeholder="8080"
            id="port"
          />
        </div>
        <div className="form-group">
          <label htmlFor="login">Login</label>
          <input
            className="form-control"
            type="text"
            placeholder="kodi"
            id="login"
          />
        </div>
        <div className="form-group">
          <label htmlFor="password">Password</label>
          <input
            className="form-control"
            type="password"
            placeholder="kodi"
            id="password"
          />
        </div>
        <div className="form-group">
          <button type="submit" className="btn btn-secondary">
            Save
          </button>{' '}
          <button type="submit" className="btn btn-secondary">
            Test
          </button>
        </div>
      </div>
    );
  }
}

export default Settings;

// src/components/Settings.vue
<template>
    <div class="fields container">
        <form>
        <div class="form-group row">
            <label for="example-text-input" class="col-2 col-form-label">IP</label>
            <div class="col-10">
                <input class="form-control" type="text" placeholder="IP Adress" id="example-text-input">
            </div>
        </div>
        <div class="form-group row">
            <label for="example-search-input" class="col-2 col-form-label">Port</label>
            <div class="col-10">
                <input class="form-control" type="search" placeholder="Port" id="example-search-input">
            </div>
        </div>
        <div class="form-group row">
            <label for="example-email-input" class="col-2 col-form-label">Login</label>
            <div class="col-10">
                <input class="form-control" type="email" placeholder="Login" id="example-email-input">
            </div>
        </div>
        <div class="form-group row">
            <label for="example-url-input" class="col-2 col-form-label">Pass</label>
            <div class="col-10">
                <input class="form-control" type="url" placeholder="Pass" id="example-url-input">
            </div>
        </div>
        <button type="submit" class="btn btn-secondary">Save</button>
        </form>
    </div>

</template>

<script>
  export default {
    data () {
      return {
        ip: '',
        port: '',
        user: '',
        pw: ''
      };
    }
  };
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
    .btn {
        margin-bottom: 10px;
    }
</style>
